# Generated by Django 5.0.4 on 2024-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
