# Generated by Django 5.0.4 on 2024-05-04 07:13

import api_keys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0002_apikey_last_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(default=api_keys.models.default_expires_at),
        ),
    ]
